### ISSUE TITLE
Payment status MollieModels.Payment.PaymentStatus.Charged_Back removed?

### ISSUE THREAD

**Issue by c-lamont** [Viincenttt/MollieApi#199] opened 2020-11-13 11:59 UTC
Just updated to 2.1 and I noticed that the `Charged_Back` status has been removed. 
Is it somewhere else, or is there another value I need to use that evaluates to the payment being charged back?

**Comment by Viincenttt** [comment] 2020-11-16 19:06
Closing this one as it was a duplicate of #200

**Closed by Viincenttt** 2020-11-16 19:06 UTC
