### ISSUE TITLE
Async methods deadlock in web environment

### ISSUE THREAD

**Issue by markwemekamp** [Viincenttt/MollieApi#14] opened 2016-09-21 12:43 UTC
I was asked to implement Mollie into an existing webapp but for some reason the CreatePaymentAsync never returns in the web environment. I did a small test using a console application and the same credentials and that worked fine.

I did some research and it turns out the async methods deadlock for some reason. According to [this](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) article the await calls can be supplied with an extra method call to `ConfigureAwait(false)`

I've added this method call to all async calls in MollieClient and everything works perfect now. For example: `IRestResponse response = await this._restClient.ExecuteTaskAsync(request).ConfigureAwait(false);`

Can I do a pull request for this code or did I introduce a new problem/risk?

**Comment by reinoutkool** [comment] 2016-09-21 14:14
same here, calling the createpaymentasync feezes the website.
worked fine before!

**Comment by Viincenttt** [comment] 2016-09-21 14:47
Thank you for bringing this to my attention. I will investigate this issue as soon as possible.

**Comment by markwemekamp** [comment] 2016-09-21 15:11
I added a pull request with my fix, see for yourself if you want to include it :)

**Comment by Viincenttt** [comment] 2016-09-21 15:50
Instead  of adding ConfigureAwait to all methods, I think you could get away with only adding it the following line in the ExecuteRequestAsync method of the MollieClient class: 
IRestResponse response = await this._restClient.ExecuteTaskAsync(request);
This is because every requests eventually ends up in this method. 

Unfortunatly I am not able to reproduce the issue using the demo web application. Can you remove all ConfigureAwait calls and add my suggestion to see if it works in your situation?

**Comment by reinoutkool** [comment] 2016-09-21 15:56
,THe problem started in my case, after updating Telerik for the project to the latest version

**Comment by markwemekamp** [comment] 2016-09-21 16:58
@Viincenttt I tried adding it only to that method, it worked but as soon as it reached the next await (`await this.PostAsync<PaymentResponse>("payments", paymentRequest)`) it deadlocked there. Only when I added it to all awaits the payment succeeded. Weird problem, never encountered it before

**Comment by Viincenttt** [comment] 2016-09-21 17:41
Hi Mark,

I am not 100% sure, but I think you are having the deadlock issues because your controller methods probably aren't async and you are trying to access the "Result"  property of the async methods of the MollieClient. Is this correct? 

This would explain why the demo web application doesn't have any issues, since all it's controller methods are async. A temporary workaround could be for you to make your controller actions async so this problem doesn't occur. 

I will continue testing your solution for a few days and hope to release a new version as soon as possible. 

Thanks for helping out! 

Kind regards,
Vincent

**Comment by markwemekamp** [comment] 2016-09-21 19:05
Hi Vincent,
I did a quick check and the controller method was marked as async, it didn't contain an await operator so I guess it wasn't necessary in my case. The literal code I used for my testcase:
```csharp
[HttpPost]
public async Task<ActionResult> Create()
{
    PaymentRequest paymentRequest = new PaymentRequest() {
        Amount = 100,
        Description = "Test payment of the example project",
        RedirectUrl = "http://google.com"
    };

    PaymentResponse paymentResponse = mollieClient.CreatePaymentAsync(paymentRequest).Result;
    return View();
}
```

The paymentResponse variable never got set

I'll try the above case again tomorrow with a testcase that has no async keyword and one that has an await in it to see if the problem keeps occuring

**Comment by Viincenttt** [comment] 2016-09-21 20:14
Hi Mark, 

If you change your code to this, it should work:
```
[HttpPost]
public async Task<ActionResult> Create()
{
    PaymentRequest paymentRequest = new PaymentRequest() {
        Amount = 100,
        Description = "Test payment of the example project",
        RedirectUrl = "http://google.com"
    };

    await mollieClient.CreatePaymentAsync(paymentRequest);
    return View();
}
```

I basically added the await statement and removed the call to the Result property.

**Comment by markwemekamp** [comment] 2016-09-22 09:20
Hi Vincent,
This solved my problem, I reverted my code to it's orginal staat and added the await keyword and it now works as expected. Thanks!
Ps. I'll close my pull request

**Comment by Viincenttt** [comment] 2016-09-22 18:11
Hi Mark,

I still merged your pull request into the master, so other won't experience this kind of problem anymore. I have created a new release (1.3.6), where this issue is permanently fixed. 

Kind regards,
Vincent

**Closed by Viincenttt** 2016-09-22 18:11 UTC
